name: Deploy k8s

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.build-push.outputs.image_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Вход в ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | \
            docker login --username AWS --password-stdin \
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Build and Push образа
        id: build-push
        env:
          IMAGE_SHA: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/devops-backend-api:sha-${{ github.sha }}
          IMAGE_LATEST: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/devops-backend-api:latest
        run: |
          docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
          docker push $IMAGE_SHA
          docker push $IMAGE_LATEST
          echo "image_sha=$IMAGE_SHA" >> $GITHUB_OUTPUT

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name devops-cluster \
            --region ${{ vars.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        env:
          IMAGE_TAG: ${{ needs.build.outputs.image_sha }}
        run: |
          helm upgrade backend-api ./helm/backend-api \
            --reuse-values \
            --set image.name="$IMAGE_TAG" \
            --wait \
            --timeout 4m

